import asyncio
import edge_tts
import os

out_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "public", "audio")
os.makedirs(out_dir, exist_ok=True)

episodes = [
    {
        "file": "ep42-bootstrapped-to-1m-a-month.mp3",
        "voice": "en-US-AvaNeural",
        "text": "Welcome to The Scale Sessions. I'm Rachel Kim. Today, the story every bootstrapped founder needs to hear. How Rachel Kim took Luminary Beauty from ten thousand dollars a month to one million dollars a month in just fourteen months, without raising a single dollar of outside funding. Let's break down exactly how she did it, phase by phase. Phase one, months one through four. Rachel ignored paid advertising completely. Instead, she sent free products to two hundred micro influencers and reposted every piece of content they created. That content library became her creative engine, and it cost her almost nothing. Phase two, months five through nine. With proven creative in hand, she started Meta ads at five thousand dollars a month. Her advantage plus shopping campaigns had eight different videos to work with, all featuring real customers, all filmed vertically on phones. Her return on ad spend held steady above two point five. Then came month nine, the near death moment. A viral TikTok drove a thirty x spike in orders. Rachel celebrated for exactly one day, then realized she couldn't fulfill them. She sold out in six days, and her ad account kept spending against products she didn't have. By the time inventory landed three weeks later, her account performance had collapsed and took two months to recover. Her lesson. Scale fulfillment infrastructure before you scale spend. And finally, the acquisition offer. At eleven months, a strategic buyer offered five million dollars. Rachel declined. Her reasoning was simple. The brand was compounding at twenty percent month over month, which meant the same business would be worth several times more within two years. Three takeaways from Rachel's journey. One, creative volume beats budget volume in the early days. Two, operational readiness is part of marketing, not separate from it. Three, know your compounding rate, because it tells you what to say no to. That's all for this episode. See you next Tuesday."
    },
    {
        "file": "ep41-why-your-roas-is-lying.mp3",
        "voice": "en-US-AndrewNeural",
        "text": "Hey, I'm Marcus Webb, and this is The Scale Sessions. Today we're answering a question that quietly costs e-commerce brands millions of dollars every year. Is your return on ad spend number lying to you? The short answer. Almost certainly yes. Here's why. Since Apple's privacy changes, platforms lost visibility into a large share of conversions. When Meta can't see a purchase, it optimizes toward the purchases it can see, and reports numbers based on modeled, incomplete data. Meanwhile, your analytics platform measures something different again, using its own attribution window and rules. So you have three dashboards telling three different stories, and none of them match your bank account. So what should you track instead? Number one, blended MER. Total revenue divided by total ad spend, measured weekly. It's the honest headline number, because it uses revenue your accountant can verify. If blended MER is healthy, individual campaign numbers matter far less than you think. Number two, contribution margin over ninety days. First order profitability is a vanity metric in a world where email and repeat purchase drive up to a third of revenue. Know what a customer is worth before you decide what you can afford to pay for one. Number three, incrementality. This is the big one. A retargeting campaign claiming fifty thousand dollars in revenue often claims sales that would have happened anyway. Geo lift testing solves this. Run your ads heavily in one set of cities and lightly in matched cities, then compare. The difference is your true incremental lift. Brands are regularly shocked to find their best looking retargeting campaigns produce almost no incremental revenue. Your action item this week. Build one simple spreadsheet. Weekly revenue, weekly ad spend, blended MER. Track it for eight weeks before you touch another campaign setting. Decisions get dramatically easier when you trust the number you're looking at. That's it for this episode. See you next Tuesday."
    },
    {
        "file": "ep40-creative-volume-framework.mp3",
        "voice": "en-GB-RyanNeural",
        "text": "This is The Scale Sessions. I'm Tola Adeyemi. Today's question comes up in nearly every client onboarding call. How many ads is enough? Ten new creatives a week? Fifty? Today we're settling this with a framework, not a feeling. Step one. Match creative volume to spend level. Under twenty thousand dollars a month, you need four to six new creatives weekly. Twenty to one hundred thousand, aim for ten to fifteen. Above one hundred thousand monthly, plan for twenty five to forty, because at that spend level, creative fatigue is your primary tax on performance. Step two. Produce angles, not ads. Most teams sit down and make an ad. Strong teams make a decision first. Which customer tension are we speaking to? Price. Complexity. Status. Fear of missing out. Write the tension down, then brief three different creators on that single idea. Now you're not testing three ads, you're testing one angle with three expressions. When an angle wins, you've learned something you can build a quarter of creative around. Step three. Know the three hook formulas that dominate winning ads. Formula one, the visible transformation. Show the result in the first second, then explain how. Formula two, the bold claim with proof. Make a statement that sounds slightly too confident, then immediately demonstrate it. Formula three, the callout. Name your exact customer in the first line. If you sell sleep supplements, say, if you wake up at three a m every night, this is for you. It feels obvious. It works relentlessly. Step four. Watch for fatigue before it costs you. When frequency climbs past two point five and click through rate drops twenty percent from the ad's seven day average, refresh. Don't wait for performance to fall off a cliff. Your action item. Audit your last thirty days of creative. Count how many distinct angles you tested. If the answer is fewer than five, you haven't been testing creative. You've been testing variations of one bet. That's it for this episode. See you next Tuesday."
    },
    {
        "file": "ep39-email-lifecycle-system.mp3",
        "voice": "en-US-EmmaNeural",
        "text": "You're listening to The Scale Sessions. I'm Sofia Marino. Everyone says email is dead. My guest data says otherwise, and today I'm sharing the exact system behind it. At Aura Home, the lifecycle program drives thirty one percent of total company revenue. Nearly one in three dollars comes from a channel most brands treat as an afterthought. Here's how the system works. It starts with six automated flows, built in this exact order. Flow one, welcome series. Four emails over ten days. This flow routinely earns the highest revenue per recipient of anything you will ever send, because new subscribers are the most interested audience you will ever have. Flow two, abandoned cart. Three messages. A reminder at four hours, social proof at twenty four hours, and a final note at seventy two hours that answers objections instead of discounting immediately. Flow three, browse abandonment. One gentle email referencing the category, never the specific product. Nobody likes being followed around a store. Flow four, post purchase. This is the one almost everyone skips, and it's a mistake. Set expectations, teach product usage, and ask for a review at the right moment. Customers who receive proper post purchase education return at nearly double the rate. Flow five, winback. Triggered at sixty, ninety, and one hundred eighty days of silence. Reactivating a lapsed customer costs a fraction of acquiring a new one. Flow six, VIP. Your top ten percent of customers by lifetime value deserve early access and genuine perks. They generate outsized revenue and your best referrals. Now, segmentation. At minimum, separate buyers from non buyers, and active customers from lapsed ones. Sending the same campaign to everyone means your message is relevant to no one. And deliverability. Keep a dedicated sending domain, authenticate it properly, and prune unengaged contacts every quarter. A clean list of fifty thousand outearns a bloated list of two hundred thousand, every single time. Your action item. Pick one flow you don't have yet, build it this week, and watch the revenue appear in thirty days. That's it for this episode. See you next Tuesday."
    },
    {
        "file": "ep38-hiring-vs-agency.mp3",
        "voice": "en-US-BrianNeural",
        "text": "I'm James Osei, and this is The Scale Sessions. Every growing brand eventually faces this decision. Should I hire an in-house media buyer, or stay with my agency? Today, an honest cost breakdown of both paths, from someone who has done both. Let's start with the real numbers. An experienced in-house media buyer commands sixty to ninety thousand dollars salary, plus roughly twenty percent in benefits and tooling. Add recruiting time, a ninety day ramp up period, and the reality that great buyers want equity or leave within two years. Total first year investment frequently exceeds one hundred twenty thousand dollars. Agency retainers typically run five to fifteen thousand dollars monthly. But here's the hidden cost nobody puts in the proposal. You get a team, not a person. Strategy, creative direction, analytics, and a backup buyer when yours goes on holiday. When an in-house buyer resigns, your account sits unsupervised until you replace them. So when does hiring in-house actually make sense? Three conditions. First, sustained spend above one hundred fifty thousand dollars per month, where the math clearly favors internal headcount. Second, advertising requires deep daily collaboration with product and inventory decisions. Third, you have senior leadership who can genuinely manage and develop the role. Below those thresholds, the agency model wins on cost, speed, and risk. Now, if you stay agency led, vet properly. Ask these five questions. One, who exactly executes my account daily, and can I speak with them? Two, what is your client retention rate? Anything under eighty percent deserves scrutiny. Three, how do you report results, and will you commit to blended metrics, not just platform numbers? Four, what does your creative process look like, and who owns it? Five, walk me through an account that failed. What happened, and what did you change afterward? That last one matters most. Agencies that can discuss failure honestly have usually learned from it. Those that can't are about to make you their next lesson. Your action item. If you're agency led, send those five questions this week. If you're in house, calculate your true fully loaded cost and compare it to your agency retainer. The answer is usually clarifying. That's it for this episode. See you next Tuesday."
    },
    {
        "file": "ep37-pre-spend-account-audit.mp3",
        "voice": "en-GB-SoniaNeural",
        "text": "The Scale Sessions. I'm Priya Nair. Before Tier Digital touches a single dollar of a new client's budget, we run a forensic audit of the entire account. Today, I'm opening that playbook publicly, because these five issues appear in ninety percent of accounts we inherit, and every one of them silently burns money. Issue one. Broken conversion tracking. Symptoms include purchase events firing twice, or revenue totals that don't move when sales clearly do. Check whether your pixel and your conversions API are deduplicating correctly. If event IDs don't match, Meta either counts purchases twice or ignores half of them entirely. Every optimization decision downstream is built on this data. Fix it first. Issue two. Structure that fights the algorithm. We regularly find accounts with fifteen campaigns, each containing one ad set and two ads. This fragments learning and starves every campaign of the conversion volume needed to exit the learning phase. Consolidate aggressively. Fewer campaigns, broader audiences, more creative per ad set. Issue three. Audience overlap. When multiple ad sets target similar people, they bid against each other in the same auctions. You literally raise your own costs. Use the audience overlap tool, merge anything sharing more than thirty percent similarity, and let broad targeting do its job. Issue four. Missing server side signals. Browser only tracking loses a significant share of conversions on iOS. A properly configured conversions API restores that signal, and in our audits it improves reported performance accuracy within weeks. It's technical, but it is the highest leverage fix on this list. Issue five. Leaky landing pages. Paid traffic converts at two percent while the page loads in six seconds on mobile. Every second of load time costs conversions, and every extra field on a form costs more. Fix page speed and message match before scaling spend, because scaling a leaking funnel just buys more leaks. Your action item this week. Pick one of the five issues, audit it today, and fix it before you spend another dollar. That's it for this episode. See you next Tuesday."
    }
]

async def generate():
    for ep in episodes:
        out_path = os.path.join(out_dir, ep["file"])
        communicate = edge_tts.Communicate(ep["text"], ep["voice"])
        await communicate.save(out_path)
        size_mb = os.path.getsize(out_path) / (1024 * 1024)
        print(f"{ep['file']} -> {size_mb:.2f} MB")

asyncio.run(generate())
